"""Update request schema

Revision ID: cd62844ec46a
Revises: c87b82024c3b
Create Date: 2026-08-15 13:09:07.345534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd62844ec46a'
down_revision: Union[str, Sequence[str], None] = 'c87b82024c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('pickup_date', sa.Date(), nullable=True))
    op.add_column('requests', sa.Column('pickup_time_slot', sa.Enum('SLOT_07_08', 'SLOT_08_09', 'SLOT_09_10', 'SLOT_10_11', 'SLOT_11_12', 'SLOT_12_13', 'SLOT_13_14', 'SLOT_14_15', 'SLOT_15_16', 'SLOT_16_17', 'SLOT_17_18', 'SLOT_18_19', 'SLOT_19_20', 'SLOT_20_21', name='pickup_time_slot_enum'), nullable=True))
    op.add_column('requests', sa.Column('pickup_address', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('pickup_postcode', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('dropoff_address', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('dropoff_postcode', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('helpers_needed', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('pickup_floor', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('pickup_has_lift', sa.Boolean(), nullable=True))
    op.add_column('requests', sa.Column('dropoff_floor', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('dropoff_has_lift', sa.Boolean(), nullable=True))
    op.add_column('requests', sa.Column('pickup_loading_minutes', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('dropoff_loading_minutes', sa.Integer(), nullable=True))
    #op.add_column('requests', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('requests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('requests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('requests', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('requests', 'updated_at')
    op.drop_column('requests', 'dropoff_loading_minutes')
    op.drop_column('requests', 'pickup_loading_minutes')
    op.drop_column('requests', 'dropoff_has_lift')
    op.drop_column('requests', 'dropoff_floor')
    op.drop_column('requests', 'pickup_has_lift')
    op.drop_column('requests', 'pickup_floor')
    op.drop_column('requests', 'helpers_needed')
    op.drop_column('requests', 'dropoff_postcode')
    op.drop_column('requests', 'dropoff_address')
    op.drop_column('requests', 'pickup_postcode')
    op.drop_column('requests', 'pickup_address')
    op.drop_column('requests', 'pickup_time_slot')
    op.drop_column('requests', 'pickup_date')
    # ### end Alembic commands ###
